"""updated data points

Revision ID: 2a31641d1aa1
Revises: 12b238e79cef
Create Date: 2020-11-11 07:43:58.343642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a31641d1aa1'
down_revision = '12b238e79cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.Enum(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
