"""update-sensor

Revision ID: 42213a756b5a
Revises: 192d288b5f7c
Create Date: 2020-12-03 16:25:52.259735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42213a756b5a'
down_revision = '192d288b5f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_column('module')

    # ### end Alembic commands ###
