"""add-timestamp-datapoint

Revision ID: 52d4af3d2c4b
Revises: 2a31641d1aa1
Create Date: 2020-11-25 01:51:50.622915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d4af3d2c4b'
down_revision = '2a31641d1aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
