"""updated-user

Revision ID: 54d83eae649a
Revises: 42213a756b5a
Create Date: 2020-12-13 06:25:26.358133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d83eae649a'
down_revision = '42213a756b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    op.drop_table('data_point')
    op.drop_table('issue')
    op.drop_table('server')
    op.drop_table('config_item')
    op.drop_table('device')
    op.drop_table('pin_out')
    op.drop_table('user')
    op.drop_table('sensor')
    op.drop_table('security_config')
    op.drop_table('server_config')
    op.drop_table('api_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('server_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('device_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('security_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('device_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sensor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('quantity', sa.VARCHAR(length=128), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=3), nullable=True),
    sa.Column('cls', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('device_id', sa.INTEGER(), nullable=True),
    sa.Column('module', sa.VARCHAR(length=1024), nullable=True),
    sa.CheckConstraint("unit IN ('Hz', 'J', 'Db', 'F', 'C', 'kWh')", name='unit'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=75), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=75), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('role', sa.VARCHAR(length=10), nullable=False),
    sa.Column('device_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("role IN ('USER', 'TECHNICIAN', 'MANAGER', 'ADMIN')", name='role'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pin_out',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('var', sa.VARCHAR(length=128), nullable=False),
    sa.Column('pin', sa.INTEGER(), nullable=False),
    sa.Column('sensor_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('description', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('location', sa.VARCHAR(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('config_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('description', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('value', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('sec_conf_id', sa.INTEGER(), nullable=True),
    sa.Column('serv_conf_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['sec_conf_id'], ['security_config.id'], ),
    sa.ForeignKeyConstraint(['serv_conf_id'], ['server_config.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('server',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=128), nullable=True),
    sa.Column('port', sa.INTEGER(), nullable=True),
    sa.Column('periodicity', sa.INTEGER(), nullable=True),
    sa.Column('device_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('type', sa.VARCHAR(length=13), nullable=False),
    sa.Column('device_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("type IN ('MAINT_REQD', 'EQUIP_DAMAGED')", name='issuetype'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_point',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=False),
    sa.Column('timestamp', sa.INTEGER(), nullable=False),
    sa.Column('sensor_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('value', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
