"""added-pinout

Revision ID: 59ad2b986ab8
Revises: b2e789b63ffa
Create Date: 2020-11-25 18:09:04.868811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ad2b986ab8'
down_revision = 'b2e789b63ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cls', sa.String(length=1024), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.String(length=128), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('description')
        batch_op.drop_column('identifier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=1024), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('quantity')
        batch_op.drop_column('cls')

    # ### end Alembic commands ###
