"""sensor-units

Revision ID: b2e789b63ffa
Revises: 52d4af3d2c4b
Create Date: 2020-11-25 17:24:30.835493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e789b63ffa'
down_revision = '52d4af3d2c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.drop_column('unit')

    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.Enum('HZ', 'J', 'DB', 'F', 'C', 'KWH', name='unit'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_column('unit')

    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
