"""update-pinout

Revision ID: c920833397e4
Revises: 59ad2b986ab8
Create Date: 2020-11-25 18:21:38.816723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c920833397e4'
down_revision = '59ad2b986ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pin_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('var', sa.String(length=128), nullable=False),
    sa.Column('pin', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pin_out')
    # ### end Alembic commands ###
