"""added-server-and-status

Revision ID: de420b9eba6e
Revises: c920833397e4
Create Date: 2020-11-26 16:47:22.451660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de420b9eba6e'
down_revision = 'c920833397e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=128), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('periodicity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.alter_column('cls',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('cls',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)

    op.drop_table('status')
    op.drop_table('server')
    # ### end Alembic commands ###
